name: CI

env:
  node.version: 16.x
  main-branch-name: master

on:
  pull_request:

jobs:
  prettier:
    name: 'Affected: Prettier'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node.version}}
          cache: 'npm'

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{env.main-branch-name}}

      - run: npm ci
      - run: npm run affected:format-check -- --base=${{env.NX_BASE}} --head=${{env.NX_HEAD}}

  lint:
    name: 'Affected: Lint'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node.version }}
          cache: 'npm'

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{env.main-branch-name}}

      - run: npm ci
      - run: npm run affected:lint -- --base=${{env.NX_BASE}} --head=${{env.NX_HEAD}}

  unit-tests:
    name: 'Affected: Unit tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node.version}}
          cache: 'npm'

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{env.main-branch-name}}

      - run: npm ci
      - run: npm run affected:test -- --base=${{env.NX_BASE}} --head=${{env.NX_HEAD}}

  e2e-tests:
    name: 'Affected: E2E tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node.version}}
          cache: 'npm'

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{env.main-branch-name}}

      - run: npm ci
      - run: npm run affected:e2e -- --base=${{env.NX_BASE}} --head=${{env.NX_HEAD}}

  build:
    name: 'Affected: Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node.version}}
          cache: 'npm'

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{env.main-branch-name}}

      - run: npm ci
      - run: npm run affected:build -- --base=${{env.NX_BASE}} --head=${{env.NX_HEAD}}
